# The test suite, distributed whole.
#
# The structural guards, their shared helper and the registers they hold
# the tree to are part of the source, not scaffolding around it: a
# release tarball that ships without them ships a tree in which none of
# the invariants can be checked. Not one of them was listed here before,
# so `make dist` produced exactly that, and nothing said so -- the
# in-tree builds and every CI job read the working copy.
#
# tests/check-dist-lists.sh holds this list to the directory in both
# directions: a file present and unlisted fails, and a line naming a file
# that has gone fails too.

EXTRA_DIST += \
tests/Makefile.mk \
tests/access_test.ps \
tests/vm_reclaim_compaction_test.ps \
tests/api_definitions_test.c \
tests/array_swap_range_test.ps \
tests/bbox_test.ps \
tests/binary_token_test.expected \
tests/binary_token_test.ps \
tests/bind_packed_test.ps \
tests/blit_access_test.ps \
tests/blit_range_test.ps \
tests/build_personality_test.ps \
tests/cacheparams_range_test.ps \
tests/callback_reentry_test.ps \
tests/check-buffer-family.sh \
tests/check-callout-bracket.sh \
tests/check-clip-writer.sh \
tests/check-device-destroy.sh \
tests/check-library-lifetime.sh \
tests/check-counter-register.sh \
tests/check-vm-growth.sh \
tests/check-device-roster.sh \
tests/check-device-facts.sh \
tests/device-facts \
tests/check-filter-facts.sh \
tests/filter-facts \
tests/check-halftone-facts.sh \
tests/check-halftone-transfer.sh \
tests/check-screen-paths.sh \
tests/halftone-facts \
tests/check-shading-facts.sh \
tests/shading-facts \
tests/check-form-facts.sh \
tests/form-facts \
tests/check-function-facts.sh \
tests/function-facts \
tests/check-colourspace-facts.sh \
tests/colourspace-facts \
tests/check-pattern-facts.sh \
tests/pattern-facts \
tests/run-image-devclip-test.sh \
tests/check-image-facts.sh \
tests/run-interrupt-fused-test.sh \
tests/image-facts \
tests/check-font-facts.sh \
tests/font-facts \
tests/check-c-held-objects.sh \
tests/c_held_objects.register \
tests/check-awk-portability.sh \
tests/check-memory-declarations.sh \
tests/check-device-skeleton.sh \
tests/check-width-comparisons.sh \
tests/check-type42-charstrings.sh \
tests/check-dict-homes.sh \
tests/check-dist-lists.sh \
tests/check-encoder-units.sh \
tests/check-env-traps.sh \
tests/check-error-names.sh \
tests/check-exported-symbols.sh \
tests/check-userdict-reach.sh \
tests/check-filter-base.sh \
tests/check-fopen-funnel.sh \
tests/check-fused-ops.sh \
tests/check-gate-map.sh \
tests/check-global-local-anchors.sh \
tests/global_local_anchors.register \
tests/check-glyph-render-route.sh \
tests/check-name-interning.sh \
tests/name_interning.register \
tests/check-guard-paths.sh \
tests/check-host-settings.sh \
tests/check-must-check.sh \
tests/check-name-registers.sh \
tests/check-narrow-cursors.sh \
tests/check-object-brace-init.sh \
tests/check-one-bytebuf.sh \
tests/check-op-references.sh \
tests/check-opsigs-writer.sh \
tests/check-page-output.sh \
tests/run-pdf-docinfo-test.sh \
tests/check-private-refs.sh \
tests/check-raster-classes.sh \
tests/check-shadowed-operators.sh \
tests/check-shared-helpers.sh \
tests/check-raster-reading.sh \
tests/check-error-quiet.sh \
tests/check-testlib.sh \
tests/testlib-facts \
tests/testlib-prepend.sh \
tests/testlib_contract_test.ps \
tests/testlib.ps \
tests/check-colour-spaces.sh \
tests/check-show-clip.sh \
tests/check-test-cost.sh \
tests/check-test-devices.sh \
tests/check-test-quality.sh \
tests/check-test-timeouts.sh \
tests/check-vecbase.sh \
tests/check-pdf-overprint.sh \
tests/check-resource-file.sh \
tests/check-compaction-safe-point.sh \
tests/check-vm-address.sh \
tests/check-vm-address-fields.sh \
tests/vm_address_fields.golden \
tests/check-raw-allocations.sh \
tests/special_entity_slots_test.c \
tests/raw_allocations.golden \
tests/check-vm-host-state.sh \
tests/span_window_test.c \
tests/vm_host_state.register \
tests/check-wrapped-bind.sh \
tests/cid_show_test.ps \
tests/clip_region_test.ps \
tests/clock_test.c \
tests/colorspace_cycle_test.ps \
tests/colorspace_matrix_test.ps \
tests/colour_range_test.ps \
tests/colour_sampling_test.ps \
tests/composite_limit_test.ps \
tests/context_jobs_test.c \
tests/context_reuse_test.c \
tests/corpus/.gitignore \
tests/corpus/README.md \
tests/corpus/bwipp/nondeterministic \
tests/corpus/bwipp/nopage \
tests/corpus/bwipp/pages \
tests/corpus/bwipp/prelude.fetched \
tests/corpus/casselman/heldout \
tests/corpus/casselman/nopage \
tests/corpus/casselman/pages \
tests/corpus/eps/nopage \
tests/corpus/eps/pages \
tests/corpus/eps/unasked \
tests/corpus/evaluate.sh \
tests/corpus/fetch.sh \
tests/corpus/share.sh \
tests/corpus/ghostscript/nondeterministic \
tests/corpus/ghostscript/nopage \
tests/corpus/ghostscript/pages \
tests/corpus/ghostscript/prelude \
tests/corpus/run-corpus-test.sh \
tests/corpus/run-eps-test.sh \
tests/counttomark_test.ps \
tests/dct_truncated_test.ps \
tests/dev_gray_row_test.ps \
tests/dev_rect_test.c \
tests/record_test.c \
tests/spill_test.c \
tests/record_cost_test.c \
tests/device-fleet.sh \
tests/device_completion_test.ps \
tests/device_contract_test.ps \
tests/device_destroy.golden \
tests/library_statics.golden \
tests/counters.golden \
tests/vm_growth.golden \
tests/shared_helpers.exempt \
tests/raster_reading.exempt \
tests/one_implementation.exempt \
tests/direct_comm.exempt \
tests/device_destroy_test.ps \
tests/device_dictstack_test.ps \
tests/operator_dictstack_test.ps \
tests/window_device_test.ps \
tests/window_getpix_test.ps \
tests/device_private_test.ps \
tests/device_features_test.ps \
tests/device_getpix_destroyed_test.ps \
tests/device_ground_test.ps \
tests/device_restore_retired_test.ps \
tests/device_retire_restored_test.ps \
tests/dict_capacity_field_test.c \
tests/dict_grow_test.c \
tests/dict_hash_spread_test.c \
tests/dict_homes.golden \
tests/dict_undef_reslot_test.c \
tests/dsc_parse_test.c \
tests/edit_stream_close_test.c \
tests/empty_clip_test.ps \
tests/encoder_units.golden \
tests/entity_limit_test.ps \
tests/error_dict_test.ps \
tests/error_unwind_test.ps \
tests/execform_cache_test.ps \
tests/exported_symbols.golden \
tests/userdict_parked.golden \
tests/userdict_reach.golden \
tests/file_handle_test.c \
tests/file_lifetime_test.ps \
tests/file_refusal_test.ps \
tests/filenameforall_large_test.ps \
tests/fill_span_test.ps \
tests/filter_abandon_test.ps \
tests/filter_close_eod_test.ps \
tests/filter_conformance_test.ps \
tests/filter_encode_pad_test.ps \
tests/filter_eod_test.ps \
tests/filter_leak_test.ps \
tests/filter_matrix_test.ps \
tests/filter_predictor_test.ps \
tests/fillpoly_arity_test.ps \
tests/filter_proc_test.ps \
tests/filter_source_life_test.ps \
tests/font_bigbuf_test.ps \
tests/font_cache_bound_test.ps \
tests/font_cache_evict_test.ps \
tests/font_directory_test.ps \
tests/font_serial_test.ps \
tests/form_cache_evict_test.ps \
tests/form_serial_restore_test.ps \
tests/font_glyphkey_test.ps \
tests/font_glyph_identity_test.ps \
tests/font_glyph_colour_test.ps \
tests/font_face_error_test.c \
tests/font_face_cycle_test.c \
tests/memory_grow_test.c \
tests/font_face_release_test.ps \
tests/font_leak_test.ps \
tests/font_private_test.ps \
tests/font_type1_noaccess_test.ps \
tests/font_type1_sparse_subrs_test.ps \
tests/noface_refusal_test.ps \
tests/forall_large_test.ps \
tests/free_list_admission_test.c \
tests/free_list_recovery_test.c \
tests/free_list_size_rule_test.c \
tests/table_row_reuse_test.c \
tests/span_sort_test.c \
tests/vm_compaction_test.c \
tests/free_scan_test.ps \
tests/function_matrix_test.ps \
tests/fused_equivalence_test.ps \
tests/gc_clip_region_test.ps \
tests/gc_deep_chain_test.ps \
tests/gc_diagnostics_test.ps \
tests/gc_large_dict_pressure_test.ps \
tests/gc_large_dict_test.ps \
tests/gc_save_view_test.ps \
tests/gc_stack_segments_test.ps \
tests/gc_mark_failure_test.c \
tests/job_control_test.c \
tests/job_isolation_test.c \
tests/job_snapshot_balance_test.c \
tests/job_stream_test.c \
tests/gc_marking_test.c \
tests/global_vm_invariant_test.ps \
tests/local_vm_invariant_test.ps \
tests/vm_account_test.ps \
tests/vm_page_return_test.c \
tests/run-vm-page-return-test.sh \
tests/run-local-vm-invariant-test.sh \
tests/golden/manifest-large.sha256 \
tests/golden/manifest.sha256 \
tests/golden_page.ps \
tests/golden_pages.ps \
tests/band_loop_test.ps \
tests/band_sparse_test.ps \
tests/band_report_test.ps \
tests/band_format_test.ps \
tests/band_writer_test.ps \
tests/band_device_test.ps \
tests/band_campaign_test.ps \
tests/band_replay_cost_test.ps \
tests/band_budget_test.ps \
tests/page_lifetime_test.ps \
tests/record_image_test.ps \
tests/record_glyph_test.ps \
tests/record_excess_test.ps \
tests/record_spill_test.ps \
tests/record_short_test.ps \
tests/form_band_test.ps \
tests/form_nest_test.ps \
tests/record_span_test.ps \
tests/record_replay_test.ps \
tests/record_screen_test.ps \
tests/region_replay_test.ps \
tests/gate-map \
tests/gate.sh \
tests/graphics_load_stop_test.c \
tests/graphics_regression_test.ps \
tests/graphicsdict_slots.golden \
tests/gstate_matrix_test.ps \
tests/gstate_object_test.ps \
tests/guard-paths.sh \
tests/halftone_cell_test.ps \
tests/halftone_matrix_test.ps \
tests/host_settings.golden \
tests/idiom_test.ps \
tests/image_matrix_test.ps \
tests/imaging_bbox_test.ps \
tests/internal_debug_ops_test.ps \
tests/interrupt_test.ps \
tests/isolation_test.ps \
tests/large_object_test.ps \
tests/listing.awk \
tests/meson-tests.sh \
tests/lockdown_test.c \
tests/loop_exit_test.ps \
tests/lsan.supp \
tests/mask_cache_range_test.ps \
tests/matrix_backup_test.c \
tests/memory_bounds_test.c \
tests/must_check.golden \
tests/name_intern_test.ps \
tests/name_length_test.c \
tests/namespace_test.ps \
tests/narrow_cursors.golden \
tests/nographics_test.ps \
tests/numstring_decode_test.ps \
tests/op_bind_test.ps \
tests/op_bytesavailable_test.ps \
tests/op_closed_read_test.ps \
tests/op_compare_test.ps \
tests/op_context_test.ps \
tests/op_control_test.ps \
tests/op_cvi_test.ps \
tests/op_cvn_test.ps \
tests/op_cvs_test.ps \
tests/op_cvrs_test.ps \
tests/op_dict_capacity_test.ps \
tests/op_dictstack_test.ps \
tests/op_dispatch_typecheck_test.ps \
tests/op_env_test.ps \
tests/op_error_restore_test.ps \
tests/op_file_access_test.ps \
tests/op_file_edges_test.ps \
tests/op_file_limit_test.ps \
tests/op_filenameforall_test.ps \
tests/op_fontcache_test.ps \
tests/op_glyphcontext_test.ps \
tests/op_gstate_types_test.ps \
tests/op_hexstring_test.ps \
tests/op_index_type_test.ps \
tests/op_initgraphics_test.ps \
tests/op_intoverflow_test.ps \
tests/op_literal_test.ps \
tests/op_lookups.golden \
tests/op_loop_depth_test.ps \
tests/op_math_test.ps \
tests/op_matrix_gstate_test.ps \
tests/op_operand_shapes_test.ps \
tests/op_operand_types_test.ps \
tests/op_packing_test.ps \
tests/op_path_test.ps \
tests/op_printdepth_test.ps \
tests/printobject_overflow_test.ps \
tests/op_proc_filter_test.ps \
tests/op_radix_test.ps \
tests/op_readline_test.ps \
tests/op_readstring_test.ps \
tests/op_rect_test.ps \
tests/op_reference_test.ps \
tests/op_resource_test.ps \
tests/op_showstate_test.ps \
tests/op_status_test.ps \
tests/op_string_filter_test.ps \
tests/op_subfiledecode_test.ps \
tests/op_time_test.ps \
tests/op_userparams_test.ps \
tests/op_vm_param_test.ps \
tests/op_vmreclaim_test.ps \
tests/op_wrapsig_test.ps \
tests/operator_install_refusal_test.c \
tests/outline_font_test.ps \
tests/output_buffer_release_test.c \
tests/oversize_page_test.ps \
tests/page_cover_test.ps \
tests/page_extent_test.ps \
tests/page_handlers_test.ps \
tests/page_semantics_test.c \
tests/path_bounds_test.ps \
tests/path_confine_test.c \
tests/path_recycle_test.ps \
tests/name_lookup_cost_test.ps \
tests/path_walk_cost_test.ps \
tests/pattern_phase_test.ps \
tests/pattern_space_test.ps \
tests/colour_space_family_test.ps \
tests/custom_color_test.ps \
tests/filter_family_test.ps \
tests/pdf_append_fail_test.ps \
tests/pdf_bigfill_test.ps \
tests/pdf_global_vm_test.ps \
tests/pdf_pipe_test.ps \
tests/privatedict_install_test.ps \
tests/quit_run_test.ps \
tests/raster_buffer_format_test.c \
tests/raster_reference_test.c \
tests/raster_class_test.ps \
tests/raster_extent_test.c \
tests/raster_row_test.ps \
tests/refusal_report_test.ps \
tests/reloc_fused_test.ps \
tests/reloc_stress_test.ps \
tests/render-differ.sh \
tests/render_classes_test.ps \
tests/resource_load_test.c \
tests/resource_matrix_test.ps \
tests/roll_test.ps \
tests/run_invalid_context_test.c \
tests/run-append-fail-test.sh \
tests/run-bbox-test.sh \
tests/run-bintok-test.sh \
tests/run-clean-startup-test.sh \
tests/run-cli-options-test.sh \
tests/run-colour-range-test.sh \
tests/run-device-contract-test.sh \
tests/run-device-destroy-test.sh \
tests/run-device-features-test.sh \
tests/run-device-getpix-test.sh \
tests/run-device-ground-test.sh \
tests/run-device-quit-test.sh \
tests/run-device-restore-test.sh \
tests/run-devices-test.sh \
tests/run-dsc-tool-test.sh \
tests/run-error-binary-test.sh \
tests/run-error-format-test.sh \
tests/run-examples-test.sh \
tests/run-file-lifetime-test.sh \
tests/run-file-limit-test.sh \
tests/run-filenameforall-large-test.sh \
tests/run-gc-diagnostics-test.sh \
tests/run-gc-pressure-test.sh \
tests/run-golden-render.sh \
tests/run-record-image-test.sh \
tests/run-record-glyph-test.sh \
tests/run-record-short-test.sh \
tests/run-form-band-test.sh \
tests/run-form-nest-test.sh \
tests/run-record-span-test.sh \
tests/run-record-replay-test.sh \
tests/run-record-screen-test.sh \
tests/run-record-excess-test.sh \
tests/run-record-spill-test.sh \
tests/run-band-loop-test.sh \
tests/run-band-sparse-test.sh \
tests/run-band-report-test.sh \
tests/run-band-format-test.sh \
tests/run-band-writer-test.sh \
tests/run-band-device-test.sh \
tests/run-band-campaign-test.sh \
tests/run-band-replay-cost-test.sh \
tests/run-band-extent-test.sh \
tests/run-band-route-test.sh \
tests/run-band-select-test.sh \
tests/run-band-budget-test.sh \
tests/run-page-lifetime-test.sh \
tests/run-page-lifetime-truetype-test.sh \
tests/run-region-replay-test.sh \
tests/run-imaging-bbox-test.sh \
tests/run-jpeg-refusal-test.sh \
tests/run-leak-test.sh \
tests/run-interrupt-test.sh \
tests/run-multipage-test.sh \
tests/run-nographics-test.sh \
tests/run-oversize-page-test.sh \
tests/run-page-cover-test.sh \
tests/run-global-vm-invariant-test.sh \
tests/run-pdf-consumer-test.sh \
tests/run-pdf-global-vm-test.sh \
tests/run-pdf-pipe-test.sh \
tests/run-pdf-test.sh \
tests/run-cli-param-test.sh \
tests/run-png-filter-test.sh \
tests/run-pngalpha-test.sh \
tests/run-ppm-test.sh \
tests/run-profile.sh \
tests/run-ps-test.sh \
tests/run-raster-formats-test.sh \
tests/run-refusing-target-test.sh \
tests/run-reloc-stress-test.sh \
tests/run-render-differ-test.sh \
tests/run-setpagedevice-failure-test.sh \
tests/run-statementedit-test.sh \
tests/run-strict-ps-test.sh \
tests/run-svg-clipid-test.sh \
tests/run-svg-test.sh \
tests/run-vecout-gc-test.sh \
tests/run-vm-image-test.sh \
tests/run-file-refusal-test.sh \
tests/run-cli-sandbox-test.sh \
tests/run-font-name-steer-test.sh \
tests/run-vm-threshold-test.sh \
tests/run-vm-image-load-test.sh \
tests/run-vendor-bwipp.sh \
tests/run-view-usage-test.sh \
tests/run_input_close_test.c \
tests/run_status_test.c \
tests/cli_sandbox_test.ps \
tests/font_name_steer_test.ps \
tests/font_name_steer_probe.ps \
tests/sandbox_contexts_test.c \
tests/sandbox_root_test.c \
tests/sandbox_test.c \
tests/save_backup_extent_test.c \
tests/save_restore_ctm_test.ps \
tests/save_restore_matrix_test.ps \
tests/save_restore_sweep_cost_test.ps \
tests/save_restore_test.ps \
tests/scanner_eof_test.ps \
tests/sealed_dict_restore_test.c \
tests/semantics_test.ps \
tests/setdash_finite_test.ps \
tests/setpagedevice_failure_test.ps \
tests/shadowed_operators.golden \
tests/show_clip_routes.golden \
tests/show_clip_test.ps \
tests/show_pattern_test.ps \
tests/showop_matrix_test.ps \
tests/single_instance_test.c \
tests/sparse_rows_test.ps \
tests/stack_bounds_test.c \
tests/stack_peek_bound_test.c \
tests/stack_push_refusal_test.c \
tests/startup_device_test.c \
tests/startup_surface_api_test.c \
tests/startup_surface_test.ps \
tests/stencil_mask_size_test.ps \
tests/strbuf_test.c \
tests/stream_exec_test.ps \
tests/string_bounds_test.c \
tests/subinterval_retention_test.ps \
tests/svg_append_fail_test.ps \
tests/tamper_dispatch_test.ps \
tests/run-glyph-page-test.sh \
tests/run-halftone-drain-test.sh \
tests/run-lzwencode-early-test.sh \
tests/run-dps-test.sh \
tests/run-job-page-test.sh \
tests/run-page-extent-test.sh \
tests/run-startup-page-test.sh \
tests/run-thin-stroke-test.sh \
tests/thin_stroke_test.ps \
tests/token_sign_test.ps \
tests/trapping_test.ps \
tests/type42_charstrings_test.ps \
tests/valgrind.supp \
tests/vecout_gc_test.ps \
tests/verdict.sh \
tests/vm_image_test.c \
tests/vm_image_load_test.c \
tests/vm_test.ps \
tests/vm_threshold_test.ps \
tests/wrapped_bind.golden \
tests/wrapped_bind_test.ps \
tests/wrapped_save_test.ps \
tests/wrapsave_bank_test.ps \
tests/wrapsave_context_test.c \
tests/xpost_test.h
