xpost_data_src = files([
  'clip.ps',
  'err.ps',
  'graphics.ps',
  'device.ps',
  'color.ps',
  'image.ps',
  'pgmimage.ps',
  'pbmimage.ps',
  'ppmimage.ps',
  'tiffimage.ps',
  'nulldev.ps',
  'bboxdev.ps',
  'recorddev.ps',
  'pdfwrite.ps',
  'svgwrite.ps',
  'dscwrite.ps',
  'gstate.ps',
  'path.ps',
  'paint.ps',
  'resource.ps',
  'pattern.ps',
  'shade.ps',
  'cid.ps',
  'font.ps',
  'init.ps',
  'prepr.ps',
  'qsort.ps'
])

install_data(xpost_data_src,
  install_dir: dir_pkgdata
)
