#!/usr/bin/env python3
# The identity of this build, as one number.
#
# A build stamp made only of the version string cannot tell one build of a
# version from another, so an image written before a rebuild is read after
# it. The structure sizes and the operator table catch most of what a
# rebuild changes; what they do not catch is C that leaves every structure
# the same shape and every boot file untouched. This hashes what the build
# was made OUT OF instead of what it calls itself: every source and header,
# by name and bytes, and the compiler and flags it was built with.
#
# The files are hashed each on its own and the answers added, so the whole
# does not depend on the order a listing gives them in, and the count goes
# in as well so that a file removed is a difference. Same inputs give the
# same number, so a reproducible build stays reproducible.
import sys, os, glob

SEED = 5381

def h_bytes(h, b):
    for c in b:
        h = ((h * 33) ^ c) & 0xFFFFFFFF
    return h

def h_text(h, s):
    return h_bytes(h, s.encode("utf-8"))

def main():
    out = sys.argv[1]
    root = sys.argv[2]
    config = sys.argv[3]          # the generated config.h, in the build tree
    extra = sys.argv[4:]          # compiler id, version, flags
    total = 0
    files = 0
    paths = []
    for pat in ("src/**/*.c", "src/**/*.h", "meson.build"):
        paths += sorted(glob.glob(os.path.join(root, pat), recursive=True))
    # The generated configuration answers for everything the build was
    # configured with -- which options are on, what the host has, and any
    # value taken from the environment at configure time. Two builds of one
    # source can differ in nothing else, and a stamp that could not tell
    # them apart let an image written by one be read by the other.
    if os.path.exists(config):
        paths.append(config)
    for path in paths:
        h = h_text(SEED, os.path.basename(path))
        with open(path, "rb") as f:
            h = h_bytes(h, f.read())
        total = (total + h) & 0xFFFFFFFF
        files += 1
    total = h_bytes(total, str(files).encode())
    for e in extra:
        total = h_text(total, e)
    text = ("/* Generated by tools/build-id.py. What this build was made out\n"
            "   of, as one number: every source and header by name and bytes,\n"
            "   the file count, and the compiler and flags. */\n"
            "#ifndef XPOST_BUILD_ID_H\n#define XPOST_BUILD_ID_H\n"
            "#define XPOST_BUILD_ID 0x%08xu\n#endif\n" % total)
    old = None
    if os.path.exists(out):
        with open(out) as f:
            old = f.read()
    if old != text:                # do not touch it when nothing moved
        with open(out, "w") as f:
            f.write(text)

main()
