#!/usr/bin/env python3
"""
Generate tests/namespace_test.ps -- a startup-cleanliness regression test.

It captures the exact set of name keys systemdict exposes in a freshly started
interpreter and emits a test asserting that, after startup:

  - userdict is empty        (a program starts with a clean private namespace)
  - globaldict is empty
  - systemdict holds PRECISELY the captured golden set -- no more, no less

so that no internal operator, procedure or construct can leak into a
userland-visible dictionary unnoticed. A deliberate change to systemdict's public
surface (a new standard operator, say) fails the test until the golden set is
regenerated -- which makes every such change a reviewed one.

Regenerate after an intended change:
    XPOST=build/src/bin/xpost python3 tools/gen_namespace_test.py

The generator reads the live systemdict from the built interpreter, so the golden
set always reflects the current build when regenerated on purpose.
"""
import os, subprocess, sys

XP  = os.environ.get("XPOST", "build/src/bin/xpost")
ENV = dict(os.environ, XPOST_DATA_DIR=os.path.abspath("data"),
           LD_LIBRARY_PATH=os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(XP))),"lib"))

# Dump every name key of systemdict, one per line, as a plain string,
# between two markers of the program's own. The interpreter says nothing of
# its own to a run with no terminal on its standard input, so the markers
# are the first and last lines of what comes back and everything between
# them is a key. Reading them rather than counting on that is what makes a
# line of the interpreter's a hard failure here: it would have to arrive
# outside the markers, and the reader below refuses anything outside them.
# A generator that instead skipped the lines it recognised would take a
# line it did not recognise for a key and write it into the golden set.
BEGIN = "%%<<keys>>%%"
END   = "%%<</keys>>%%"
DUMP = (r"(" + BEGIN + r"\n) print"
        r" systemdict { pop dup type /nametype eq"
        r" { 128 string cvs print (\n) print }{ pop } ifelse } forall"
        r" (" + END + r"\n) print")

# systemdict names whose presence depends on the build's optional libraries
# (device loaders behind HAVE_LIBJPEG / HAVE_LIBPNG / HAVE_XCB, and the name a
# build with no face library states itself by) or the target platform (the
# win32 device). They are allowed but not required, so the golden set stays
# portable across build configurations. A name here is dropped from the
# required set and permitted whether or not this build exposes it.
OPTIONAL = {
    "NOFACES",             # !HAVE_FREETYPE2 (present)
    "loadjpegdevice",      # HAVE_LIBJPEG
    "loadpngdevice",       # HAVE_LIBPNG
    "loadpngalphadevice",  # HAVE_LIBPNG
    "loadxcbdevice",       # HAVE_XCB
    "loadwin32device",     # _WIN32 (present)
    "WIN32",               # _WIN32 (present)
    "resetfile",           # !_WIN32 (absent on Windows)
    # Display PostScript multiple-execution-context operators, installed only
    # on the --enable-dps runtime opt-in (xpost_dps_set); absent by default.
    "currentcontext",      # --enable-dps
    "fork",                # --enable-dps
    "join",                # --enable-dps
    "yield",               # --enable-dps
    "detach",              # --enable-dps
}

def live_keys():
    r = subprocess.run([XP, "-q", "--no-sandbox", "-d", "null", "/dev/stdin"],
                       input=DUMP.encode(), capture_output=True, env=ENV, timeout=60)
    lines = [s.rstrip("\r") for s in r.stdout.decode("latin1").splitlines()]
    if not lines or lines[0] != BEGIN or lines[-1] != END:
        sys.exit("the interpreter wrote something other than the key dump to "
                 "its output channel; the golden set is not regenerated from "
                 "it.\n--- what it wrote ---\n"
                 + "\n".join(lines[:12]))
    keys = lines[1:-1]
    if BEGIN in keys or END in keys:
        sys.exit("the key dump is not bracketed once; the golden set is not "
                 "regenerated from it")
    # de-dupe defensively, keep sorted for a stable, reviewable diff
    return sorted(set(keys))

def pslit(s):
    # keys never contain ( ) or backslash (verified), but escape defensively
    return "(" + s.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)") + ")"

def _rows(names):
    L, row = [], []
    for k in names:
        row.append(pslit(k) + " true")
        if len(row) == 4:
            L.append("  " + "  ".join(row)); row = []
    if row:
        L.append("  " + "  ".join(row))
    return L

def gen(keys):
    required = [k for k in keys if k not in OPTIONAL]
    optional = sorted(OPTIONAL)
    L = ["% GENERATED by tools/gen_namespace_test.py -- do not edit by hand.",
         "% Startup cleanliness: userdict and globaldict must be empty, and systemdict",
         "% must expose no name beyond the golden set below plus the build-optional",
         "% names, so no internal operator or procedure leaks into a userland-visible",
         "% dictionary. The optional names (device loaders behind an optional library,",
         "% the win32 device, the name a build with no face library states itself by)",
         "% are allowed but not required, keeping the test portable.",
         "% Prints SUCCESS iff so. Regenerate deliberately after an intended change.",
         "%",
         "% COLLECTION: this reads systemdict membership, not a memory bound. The",
         "% words vmstatus and globalvmstatus appear below only as golden key names,",
         "% so the result is the same at any collection frequency; the line also keeps",
         "% check-memory-declarations satisfied, which matches those words.",
         "",
         "% Do every definition inside a scratch dict so the test's own bookkeeping",
         "% never lands in userdict -- which is one of the things it is checking.",
         "256 dict begin",
         "/fail 0 def",
         "/bad { (FAIL: ) print print ( ) print == /fail fail 1 add def } bind def",  # PS stack: obj (msg)
         "",
         "% userland's own namespaces start empty",
         "userdict   length 0 ne { userdict   length (userdict not empty)   bad } if",
         "globaldict length 0 ne { globaldict length (globaldict not empty) bad } if",
         "",
         f"% the {len(required)} name keys every build exposes",
         "/golden <<"]
    L += _rows(required)
    L.append(">> def")
    L.append("")
    L.append("% names present only when an optional library or the platform provides them")
    L.append("/optional <<")
    L += _rows(optional)
    L.append(">> def")
    L.append("")
    L.append("% no name may leak: every systemdict name key is golden or optional")
    L.append("systemdict {")
    L.append("  pop dup type /nametype eq {")
    L.append("    128 string cvs")
    L.append("    golden 1 index known { pop }{")
    L.append("      optional 1 index known { pop }{ (unexpected systemdict key) bad } ifelse")
    L.append("    } ifelse")
    L.append("  }{ pop } ifelse")
    L.append("} forall")
    L.append("")
    L.append("% nothing is missing: every golden name key is present in systemdict")
    L.append("golden {")
    # A key given as a string is stored as the name it spells (PLRM 3.4),
    # so what comes back out of the golden set is a name already; a key
    # some other kind is asked about as it stands rather than converted.
    L.append("  pop")
    L.append("  dup type /stringtype eq { dup cvn }{ dup } ifelse")
    L.append("  systemdict exch known { pop }{ (missing systemdict key) bad } ifelse")
    L.append("} forall")
    L.append("")
    L.append("fail 0 eq { (SUCCESS) = }{ (FAILURES: ) print fail = } ifelse")
    L.append("end")
    return "\n".join(L) + "\n"

if __name__ == "__main__":
    dst = sys.argv[1] if len(sys.argv) > 1 else "tests/namespace_test.ps"
    keys = live_keys()
    if len(keys) < 100:
        sys.exit("refusing to write: only %d keys captured (interpreter error?)" % len(keys))
    open(dst, "w").write(gen(keys))
    req = sum(1 for k in keys if k not in OPTIONAL)
    print("wrote", dst, "with", req, "required and", len(OPTIONAL), "optional keys")
